Repository Team-MindWay/MindWay-v2-Front, pull requests merged in 2024-07, with the labels that each got.

#25 🔀 vercel 배포 테스트를 위한 코드 변경
  .eslintrc.json
  components/BookPage/AlertModal/style.ts
  components/BookPage/ApplicantModal/index.tsx
  components/BookPage/RecommendModal/index.tsx
  components/BookPage/index.tsx
  components/BookPage/style.ts
  components/Header/style.ts
  components/MyPage/ApplicantList/style.ts
  components/MyPage/DeleteModal/index.tsx
  components/MyPage/EditModal/index.tsx
  components/MyPage/MyList/index.tsx
  types/asset/ColorType.ts
Labels: 🌏 Type: Deploy, 3️⃣ Priority: Low

#26 🔀메인페이지 퍼블리싱
  asset/svg/Bar.tsx
  asset/svg/Notice.tsx
  asset/svg/RankingVerticalBar.tsx
  asset/svg/SeeMore.tsx
  asset/svg/VerticalBar.tsx
  components/BookPage/style.ts
  components/MainPage/EventCalendar/index.tsx
  components/MainPage/EventCalendar/style.ts
  components/MainPage/NotificationHeader/index.tsx
  components/MainPage/NotificationHeader/style.ts
  components/MainPage/ReadinKing/index.tsx
  components/MainPage/ReadinKing/style.ts
  components/MainPage/ReadingGoal/index.tsx
  components/MainPage/ReadingGoal/style.ts
  components/MainPage/index.tsx
  components/MainPage/style.ts
  package.json
  pages/index.tsx
  styles/globals.css
  yarn.lock
Labels: 🎨 Type: Publishing

#28 🔀 GAuthText 이름 변경
  asset/svg/GAuthLoginText.tsx
  asset/svg/GauthText.tsx
  asset/svg/index.ts
  components/AuthPage/index.tsx
  components/LoginPage/index.tsx
Labels: ⚡Type: Simple, 🌏 Type: Deploy, 2️⃣ Priortiy: Medium

#29 🔀 Redux-persist 도입
  components/MyPage/MyList/index.tsx
  pages/_app.tsx
  store/index.ts
  store/user.ts
Labels: ✨ Type: Feature, 🐞 Type: Bug, 1️⃣ Priority: High

#30 add unit text
  asset/svg/DeleteButtonIcon.tsx
  components/common/Input/index.tsx
  components/common/Input/style.ts
  types/components/InputType.ts
Labels: ⚡Type: Simple, 3️⃣ Priority: Low

#34 🔀독서왕 로직 추가
  asset/svg/RankingVerticalBarNone.tsx
  components/MainPage/ReadinKing/index.tsx
  types/components/RankType.ts
Labels: ✨ Type: Feature, 2️⃣ Priortiy: Medium
